# Sync env from project root .env to website + server (local only; never committed).
# Usage: .\scripts\sync-env.ps1

$root = Split-Path $PSScriptRoot -Parent
$envFile = Join-Path $root ".env"
if (-not (Test-Path $envFile)) {
    Write-Error "Missing $envFile - copy .env.example to .env first."
    exit 1
}

function Read-DotEnv([string]$path) {
    $map = @{}
    Get-Content $path | ForEach-Object {
        $line = $_.Trim()
        if ($line -eq "" -or $line.StartsWith("#")) { return }
        $i = $line.IndexOf("=")
        if ($i -lt 1) { return }
        $key = $line.Substring(0, $i).Trim()
        $val = $line.Substring($i + 1).Trim()
        $map[$key] = $val
    }
    return $map
}

function Format-MongoUri([string]$uri) {
    if (-not $uri) { return $uri }
    $out = $uri.Trim()
    if ($out -match '^(mongodb(\+srv)?://)([^:/]+):([^@]+)@(.+)$') {
        $prefix = $Matches[1]
        $user = $Matches[3]
        $pass = $Matches[4]
        $suffix = $Matches[5]
        # Skip re-encoding if password already contains percent-escapes (e.g. %2F)
        $encodedPass = if ($pass -match '%[0-9A-Fa-f]{2}') { $pass } else { [System.Uri]::EscapeDataString($pass) }
        $out = "${prefix}${user}:${encodedPass}@${suffix}"
    }
    if ($out -match '\?=$' -or $out -match '\?$') {
        $out = $out.TrimEnd('?') + '?retryWrites=true&w=majority'
    } elseif ($out -notmatch 'retryWrites=') {
        $sep = if ($out.Contains('?')) { '&' } else { '?' }
        $out = "${out}${sep}retryWrites=true&w=majority"
    }
    return $out
}

$env = Read-DotEnv $envFile
$apiBase = $env["API_BASE_URL"]
$mongo = Format-MongoUri $env["MONGODB_URI"]

$websiteDir = Join-Path $root "LifePatternAI_Website"
if (Test-Path $websiteDir) {
    $webLines = @(
        "# Auto-generated by scripts/sync-env.ps1 - do not commit",
        "# Vercel: copy NEXT_PUBLIC_API_BASE_URL to Project Environment Variables",
        ""
    )
    if ($apiBase) {
        $webLines += "NEXT_PUBLIC_API_BASE_URL=$apiBase"
    } else {
        $webLines += "# NEXT_PUBLIC_API_BASE_URL=https://your-service.onrender.com"
    }
    $webOut = Join-Path $websiteDir ".env.local"
    $webLines | Set-Content -Path $webOut -Encoding utf8
    Write-Host "Wrote $webOut"
}

$serverDir = Join-Path $root "server"
if (Test-Path $serverDir) {
    $serverLines = @(
        "# Auto-generated by scripts/sync-env.ps1 - do not commit",
        ""
    )
    if ($env["ADMIN_EMAIL"]) { $serverLines += "ADMIN_EMAIL=$($env['ADMIN_EMAIL'])" }
    if ($env["ADMIN_PASSWORD"]) { $serverLines += "ADMIN_PASSWORD=$($env['ADMIN_PASSWORD'])" }
    if ($mongo) {
        $serverLines += "MONGODB_URI=$mongo"
    } else {
        $serverLines += "MONGODB_URI="
        $serverLines += "# Add MONGODB_URI to root .env then run sync-env.ps1 again"
    }
    $serverLines += "PORT=3000"
    $serverOut = Join-Path $serverDir ".env"
    $serverLines | Set-Content -Path $serverOut -Encoding utf8
    Write-Host "Wrote $serverOut"
}

if ($apiBase -match "192\.168\.|10\.0\.2\.2|127\.0\.0\.1|localhost") {
    Write-Warning "API_BASE_URL is local/LAN. Vercel production needs your public Render HTTPS URL."
}

Write-Host "Done."
